export const agentStyles = {
  panel: "agent-trace-panel grid gap-mc-4 animate-[page-fade-in_var(--motion-duration-normal)_var(--motion-ease-standard)] motion-reduce:animate-none",
  heading: "grid gap-mc-1 [&_h3]:m-[0]",
  toolbar: "agent-run-toolbar flex flex-wrap gap-mc-2",
  toolbarItem: "rounded-mc-pill border border-mc-border-subtle bg-mc-subtle px-mc-2 py-mc-1 text-mc-caption font-mc-semibold text-mc-secondary",
  error: "agent-error text-mc-danger",
  card: "agent-trace-card block rounded-[18px] border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-bg-surface)_88%,transparent)] p-[14px] [box-shadow:none] transition-[background,border-color,box-shadow] duration-[var(--motion-duration-fast)]",
  running: "agent-running-card flex items-center gap-mc-3 border-mc-border-subtle bg-mc-info-soft",
  liveDot: "live-dot h-mc-2 w-mc-2 rounded-full bg-mc-success",
  label: "agent-card-label text-mc-caption font-mc-semibold uppercase tracking-[0.04em] text-mc-muted",
  title: "agent-card-title inline-flex items-center gap-mc-2 text-mc-text",
  final: "agent-final-card border-mc-border-subtle",
  timeline: "agent-timeline relative grid gap-[14px]",
  timelineStep: "agent-timeline-step relative grid grid-cols-[22px_minmax(0,1fr)] gap-mc-3 border-l-2 border-mc-border-subtle",
  marker: "timeline-marker relative z-[1] inline-flex h-[21px] w-[21px] items-center justify-center rounded-[999px] border-4 border-mc-surface bg-mc-brand shadow-[0_0_0_1px_rgba(23,23,23,0.12)]",
  timelineContent: "timeline-content grid gap-[10px]",
  stepHeading: "agent-step-heading flex items-baseline justify-between gap-[10px] [&>span]:text-mc-caption [&>span]:font-mc-semibold [&>span]:text-mc-muted [&>strong]:inline-flex [&>strong]:items-center [&>strong]:gap-mc-2",
  fields: "agent-tool-fields my-[10px] grid grid-cols-3 gap-mc-2 max-[720px]:grid-cols-1",
  field: "rounded-mc-sm border border-mc-border bg-mc-subtle p-mc-2 [&>span]:block [&>span]:text-mc-badge [&>span]:font-mc-semibold [&>span]:text-mc-muted [&>strong]:block [&>strong]:[overflow-wrap:anywhere]",
  plannerSummary: "planner-summary grid gap-mc-1 [&>span]:text-mc-caption [&>span]:font-mc-semibold [&>span]:text-mc-muted [&>p]:m-[0]",
  list: "planner-step-list m-[0] mt-mc-3 grid list-none gap-mc-2 p-[0]",
  plannerStep: "planner-step flex w-full gap-[10px] rounded-mc-md border border-mc-border p-mc-2 [&_small]:block [&_small]:text-mc-caption [&_small]:text-mc-muted [&_p]:m-[0] [&_p]:mt-mc-1",
  completed: "border-mc-success-soft bg-mc-success-soft",
  traceList: "agent-trace-list m-[0] mt-mc-3 grid list-none gap-mc-2 p-[0]",
  traceItem: "rounded-mc-md border border-mc-border-subtle bg-mc-subtle p-mc-3 [&_small]:ml-mc-2 [&_small]:text-mc-caption [&_small]:text-mc-muted",
  observationList: "agent-observation-list grid gap-mc-3",
  observationItem: "agent-observation-item [&_a]:break-all [&_a]:text-mc-brand-hover [&_p]:text-[13px] [&_p]:leading-[1.55] [&_p]:text-mc-muted [&_small]:text-mc-caption [&_small]:text-mc-muted",
  toolError: "agent-tool-error rounded-mc-md border border-mc-danger bg-mc-danger-soft p-mc-3 text-mc-danger [&_p]:m-[0] [&_p]:mt-mc-1",
  empty: "empty-agent-state grid gap-mc-2 rounded-mc-lg border border-dashed border-mc-border bg-mc-subtle p-mc-5 [&_h2]:m-[0] [&_p]:m-[0]",
  emptyExamples: "agent-empty-examples m-mc-4 mx-auto grid max-w-[560px] list-none gap-mc-2 p-[0] text-left text-mc-body-small text-mc-secondary [&_li]:rounded-mc-md [&_li]:bg-mc-subtle [&_li]:px-mc-3 [&_li]:py-mc-2"
} as const;
