export const shellStyles = {
  shell: "app-shell relative z-[1] grid h-screen min-h-[0] overflow-hidden bg-mc-app",
  ambient: "ambient-layer pointer-events-none fixed inset-0 z-0 bg-none",
  rail: "app-rail flex min-h-[0] flex-col gap-mc-6 border-r border-mc-border-subtle bg-mc-sidebar p-mc-5 shadow-none",
  workspace: "app-workspace grid min-h-[0] min-w-[0]",
  body: "workspace-body grid min-h-[0] min-w-[0] overflow-hidden",
  dock: "conversation-dock min-h-[0] min-w-[0] overflow-hidden border-r border-mc-border-subtle bg-mc-sidebar shadow-none",
  main: "workspace-main min-h-[0] min-w-[0] overflow-auto bg-mc-app",
  mobileToggle: "mobile-sidebar-toggle hidden items-center gap-mc-2 rounded-mc-pill border border-mc-border bg-mc-elevated px-mc-3 py-mc-2 text-mc-text shadow-mc-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  mobileBackdrop: "mobile-sidebar-backdrop hidden border-0 p-0 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  footnote: "rail-footnote mt-auto rounded-mc-lg border border-mc-border-subtle bg-mc-subtle p-mc-4 text-mc-muted shadow-none",
  footnoteLabel: "block text-mc-caption font-mc-semibold normal-case",
  footnoteValue: "mt-[5px] block text-mc-body-small font-mc-semibold text-mc-text",
  navigation: "primary-navigation grid gap-mc-2",
  navButton: "flex min-h-[var(--control-height-md)] w-full items-center gap-mc-3 rounded-mc-md border border-transparent bg-transparent px-mc-3 text-left text-mc-body-small font-mc-semibold text-mc-secondary hover:border-transparent hover:bg-mc-hover hover:text-mc-text focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  navButtonActive: "active border-mc-border-subtle bg-mc-brand-soft text-mc-text shadow-none",
  navGlyph: "nav-glyph grid h-[var(--icon-container-sm)] w-[var(--icon-container-sm)] place-items-center rounded-mc-sm border border-mc-border-subtle bg-mc-brand-soft text-mc-brand",
  navLock: "nav-lock ml-auto inline-flex text-mc-muted",
  topBar: "top-bar flex min-w-0 items-center justify-between gap-mc-4 border-b border-mc-border-subtle bg-mc-app px-[var(--workspace-padding-x)] shadow-none",
  topBarGroup: "flex min-w-[0] flex-nowrap items-center",
  topBarStatus: "top-bar-status gap-mc-3 overflow-hidden",
  page: "top-bar-page shrink-0 pr-mc-1 text-mc-body font-mc-semibold leading-[var(--line-height-compact)] text-mc-text",
  context: "top-bar-context whitespace-nowrap border-l border-mc-border pl-mc-3 text-mc-caption text-mc-muted",
  health: "top-bar-health inline-flex items-center gap-mc-1 whitespace-nowrap text-mc-badge font-mc-medium text-mc-muted",
  version: "top-bar-version whitespace-nowrap text-mc-badge font-mc-medium text-mc-muted",
  actions: "top-bar-actions gap-mc-2",
  authActions: "top-bar-auth-actions inline-flex items-center gap-mc-2",
  authButton: "min-h-[var(--control-height-sm)] cursor-pointer rounded-mc-pill border border-mc-border-subtle bg-mc-subtle px-mc-3 text-mc-secondary hover:bg-mc-hover hover:text-mc-text focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-50",
  user: "top-bar-user-pill rounded-mc-pill bg-mc-brand-soft px-mc-3 py-mc-1 text-mc-label font-mc-medium text-mc-text"
} as const;
