export const contextStyles = {
  panel: "context-panel shell-context-panel grid min-h-[0] grid-rows-[auto_auto_minmax(0,1fr)] overflow-hidden rounded-mc-xl border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-accent-soft)_44%,var(--color-bg-surface))] shadow-none",
  collapsed: "collapsed hidden",
  open: "open mobile-open",
  header: "shell-context-panel__header flex items-start justify-between gap-mc-3 px-mc-4 pt-mc-4 [&_h2]:m-[0] [&_h2]:text-mc-title [&_h2]:leading-[var(--line-height-heading)]",
  close: "shell-context-panel__close hidden",
  tabs: "context-tabs flex gap-mc-2 border-b border-mc-border-subtle p-mc-4",
  tab: "rounded-mc-sm border border-mc-border bg-mc-surface px-mc-3 py-[6px] text-mc-body-small text-mc-secondary hover:bg-mc-hover hover:text-mc-text focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  tabActive: "active border-mc-border-subtle bg-mc-brand-soft text-mc-text shadow-none",
  body: "context-panel-body min-h-[0] overflow-y-auto p-mc-4",
  mobileTrigger: "context-panel-mobile-trigger hidden min-h-[var(--control-height-md)] items-center rounded-mc-pill border border-mc-border bg-mc-elevated px-mc-4 text-mc-body-small font-mc-semibold text-mc-text shadow-mc-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  mobileBackdrop: "context-panel-mobile-backdrop hidden border-0 p-[0] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  panelSection: "sources-panel grid gap-mc-3",
  panelTitle: "m-[0] text-[22px] font-[720]",
  empty: "source-empty-state",
  list: "source-list grid min-h-[40px] gap-[10px]",
  card: "source-card grid grid-cols-[auto_minmax(0,1fr)] gap-x-mc-3 gap-y-mc-2 rounded-[18px] border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-bg-surface)_88%,transparent)] p-[14px] shadow-none transition-[background,border-color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:-translate-y-px hover:bg-mc-hover hover:shadow-mc-xs",
  sourceIndex: "source-index row-span-3 text-mc-caption font-mc-bold text-mc-muted",
  sourceMeta: "source-meta grid min-w-[0] gap-mc-1 [&_a]:text-mc-brand-hover [&_a]:no-underline [&_strong]:text-mc-brand-hover",
  sourceTitle: "source-title col-start-2 overflow-hidden text-ellipsis text-mc-body-small leading-[1.35] text-mc-brand-hover",
  sourcePreview: "col-start-2 m-[0] text-mc-body-small text-mc-secondary",
  sourceLink: "source-open-link col-start-2 text-mc-caption font-mc-semibold text-mc-brand-hover no-underline hover:underline",
  debugPanel: "retrieval-debug-panel grid gap-mc-4",
  debugField: "debug-field grid gap-[6px] text-mc-caption font-mc-semibold text-mc-muted",
  debugGrid: "debug-grid grid grid-cols-2 gap-mc-3 max-[720px]:grid-cols-1",
  debugChecks: "debug-checks flex gap-mc-3 text-mc-body-small text-mc-muted [&_label]:flex [&_label]:items-center [&_label]:gap-[6px]",
  debugButton: "debug-search-button min-h-[var(--control-height-md)] rounded-mc-sm bg-mc-brand px-mc-4 font-mc-semibold text-mc-inverse hover:bg-mc-brand-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-50",
  debugResults: "debug-results grid min-h-[40px] gap-[10px]",
  debugCard: "debug-result-card grid gap-mc-2 rounded-[18px] border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-bg-surface)_88%,transparent)] p-[14px] shadow-none transition-[background,border-color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:-translate-y-px hover:bg-mc-hover hover:shadow-mc-xs [&>p]:m-[0] [&>p]:text-mc-body-small [&>p]:text-mc-secondary"
} as const;
