export const chatStyles = {
  area: "chat-area product-chat relative grid h-full min-w-[0] grid-rows-[auto_auto_minmax(0,1fr)] gap-[14px] overflow-hidden px-[clamp(18px,3vw,36px)] py-mc-5",
  header: "chat-header product-hero relative grid grid-cols-[minmax(0,1fr)_auto] items-start gap-[14px] overflow-hidden rounded-mc-lg border border-transparent bg-transparent px-[0] pt-mc-2 pb-mc-1 shadow-none",
  heroTitle: "m-[0] text-mc-heading font-[760] leading-[var(--line-height-heading)] tracking-[0]",
  intro: "page-intro mt-mc-2 mb-[0] max-w-[680px] text-[15px] leading-[1.55] text-mc-secondary",
  heroStatus: "hero-status-card relative z-[1] grid min-w-[180px] self-start rounded-mc-md border border-mc-border-subtle bg-mc-subtle p-mc-3 shadow-none [&>span]:text-mc-caption [&>span]:font-mc-bold [&>span]:text-mc-muted [&>span]:uppercase [&>strong]:text-[18px]",
  controls: "chat-control-bar relative z-[2] w-full max-w-[1320px] justify-self-center rounded-[18px] border border-mc-border-subtle bg-mc-surface p-[10px] shadow-none",
  controlRow: "chat-header-actions flex w-full min-w-[0] items-center justify-between gap-mc-3",
  modeGrid: "mode-toggle mode-cards grid min-w-[0] flex-1 grid-cols-[repeat(4,minmax(130px,1fr))] gap-[6px]",
  modeButton: "min-h-[36px] whitespace-nowrap rounded-mc-sm border border-mc-border bg-mc-surface px-[10px] py-mc-2 text-left text-mc-caption font-mc-bold leading-[1.2] text-mc-secondary transition-[background-color,border-color,color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:border-mc-border-strong hover:bg-mc-hover hover:text-mc-text focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus [&>span]:inline-flex [&>span]:items-center [&>span]:gap-mc-2 [&>small]:block [&>small]:text-[11px] [&>small]:font-mc-semibold [&>small]:text-mc-muted",
  modeButtonActive: "active border-mc-border-subtle bg-mc-brand-soft text-mc-brand-active shadow-none",
  compactField: "compact-field grid min-w-[180px] gap-mc-1 text-mc-caption font-mc-bold text-mc-muted [&_select]:w-[150px] [&_select]:rounded-mc-md",
  guideButton: "mode-guide-button h-[var(--control-height-md)] rounded-mc-pill border border-mc-border-subtle bg-mc-surface px-mc-3 text-mc-label font-mc-medium text-mc-secondary transition-[background-color,border-color,color,box-shadow] duration-[var(--motion-duration-fast)] hover:bg-mc-hover hover:text-mc-text active:border-mc-border-strong active:bg-mc-selected focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  workbench: "chat-workbench grid min-h-[0] min-w-[0] grid-cols-[minmax(0,1fr)_360px] gap-mc-4 overflow-hidden",
  primaryPanel: "chat-primary-panel flex min-h-[0] min-w-[0] flex-col gap-mc-3 overflow-hidden rounded-mc-lg border border-mc-border-subtle bg-mc-surface p-mc-4 shadow-none",
  modeContext: "mode-context-row flex min-w-[0] items-center justify-between gap-mc-3",
  status: "mode-status inline-flex min-h-[34px] items-center rounded-mc-pill border border-mc-border-subtle bg-mc-subtle px-[10px] py-mc-2 text-[13px] font-mc-bold text-mc-secondary",
  details: "details-launchers flex flex-wrap gap-mc-2 [&_button]:min-h-[var(--control-height-sm)] [&_button]:rounded-mc-pill [&_button]:border [&_button]:border-mc-border-subtle [&_button]:bg-transparent [&_button]:px-mc-3 [&_button]:font-mc-medium [&_button]:text-mc-secondary [&_button]:shadow-none [&_button]:transition-[background-color,border-color,color,box-shadow] [&_button]:duration-[var(--motion-duration-fast)] [&_button:hover]:border-mc-border [&_button:hover]:bg-mc-hover [&_button:hover]:text-mc-text [&_button:focus-visible]:outline [&_button:focus-visible]:outline-2 [&_button:focus-visible]:outline-offset-2 [&_button:focus-visible]:outline-mc-border-focus",
  thread: "chat-thread min-h-[0] overflow-y-auto",
  threadWithMessages: "has-messages",
  empty: "chat-empty-state mx-auto grid w-full max-w-[960px] content-start justify-items-center gap-mc-2 overflow-y-auto px-mc-4 py-mc-5 text-center",
  emptyBrand: "empty-brand-mark mx-auto inline-flex h-[56px] w-[56px] items-center justify-center bg-transparent shadow-none",
  emptyTitle: "m-[0] text-[clamp(28px,4vw,42px)] font-[760] leading-[1.05]",
  actionGrid: "empty-action-grid mx-auto grid w-full max-w-[880px] grid-cols-4 gap-mc-3",
  action: "grid min-h-[112px] gap-mc-2 rounded-mc-lg border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-bg-surface)_88%,transparent)] p-mc-4 text-left text-mc-text transition-[background-color,border-color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:border-mc-border-strong hover:bg-mc-hover hover:shadow-mc-xs active:bg-mc-selected focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-55 [&>span:last-child]:text-mc-body-small [&>span:last-child]:text-mc-secondary",
  actionActive: "active border-mc-border-strong bg-mc-selected",
  suggestions: "suggestion-grid mt-mc-3 grid w-full max-w-[880px] grid-cols-2 gap-mc-3",
  suggestion: "min-h-[56px] rounded-[18px] border border-mc-border-subtle bg-mc-surface px-mc-4 py-mc-3 text-left font-[720] text-mc-text transition-[background-color,border-color,box-shadow] duration-[var(--motion-duration-fast)] hover:border-mc-border-strong hover:bg-mc-hover hover:shadow-mc-xs active:bg-mc-selected focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-55",
  list: "message-list grid gap-[14px]",
  message: "message grid max-w-[var(--chat-message-max-width)] grid-cols-[34px_minmax(0,1fr)] gap-mc-3",
  userMessage: "user ml-auto grid-cols-[minmax(0,1fr)_34px]",
  assistantMessage: "assistant mr-auto",
  selectedMessage: "selected",
  avatar: "message-avatar inline-flex h-[34px] w-[34px] items-center justify-center rounded-mc-circle border border-mc-border-subtle bg-mc-subtle",
  content: "message-content min-w-[0] rounded-[18px] border border-mc-border-subtle bg-[color-mix(in_srgb,var(--color-bg-surface)_92%,transparent)] p-[14px] text-mc-text shadow-none",
  userContent: "border-mc-brand-soft bg-mc-brand-soft",
  selectedContent: "ring-2 ring-mc-brand-soft",
  streamingContent: "border-mc-border bg-mc-surface",
  meta: "message-meta-row mb-mc-2 flex items-center gap-mc-2",
  role: "message-role text-mc-caption font-mc-bold uppercase text-mc-muted",
  hint: "message-context-hint text-mc-caption text-mc-muted",
  actions: "message-actions mt-mc-3 flex flex-wrap items-center gap-mc-2 opacity-0 transition-opacity duration-[var(--motion-duration-fast)] group-hover:opacity-100 group-focus-within:opacity-100 [&>button]:rounded-mc-pill [&>button]:border [&>button]:border-mc-border-subtle [&>button]:bg-mc-surface [&>button]:px-mc-2 [&>button]:py-mc-1 [&>button]:text-mc-caption hover:[&>button]:bg-mc-hover",
  feedback: "feedback-controls flex flex-wrap items-center gap-mc-2 [&>button]:rounded-mc-pill [&>button]:border [&>button]:border-mc-border [&>button]:bg-mc-surface [&>button]:px-[10px] [&>button]:py-[5px] [&>button]:text-mc-caption [&>button:hover]:border-mc-border-strong [&>button:hover]:bg-mc-hover [&>button:disabled]:cursor-not-allowed [&>button:disabled]:opacity-50 [&>span]:text-mc-caption [&>span]:text-mc-muted",
  tempPanel: "temp-file-panel grid gap-mc-3 rounded-mc-md border border-mc-border-subtle bg-mc-subtle p-mc-3",
  tempUpload: "temp-file-upload flex flex-wrap items-center gap-mc-2 [&_input]:min-w-[220px] [&_input]:flex-1",
  tempUploadButton: "min-h-[var(--control-height-md)] min-w-max rounded-mc-md border border-mc-border bg-mc-surface px-mc-4 text-mc-body-small font-mc-semibold text-mc-text transition-[background-color,border-color,color,box-shadow] duration-[var(--motion-duration-fast)] hover:border-mc-border-strong hover:bg-mc-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-55",
  tempStatus: "temp-file-status m-[0] text-mc-caption text-mc-muted",
  composer: "chat-composer grid gap-mc-2 rounded-[20px] border border-mc-border bg-mc-surface p-mc-3 shadow-mc-xs transition-[border-color,box-shadow] duration-[var(--motion-duration-fast)] focus-within:border-mc-border-focus focus-within:shadow-[var(--shadow-focus)]",
  composerWarning: "composer-warning m-[0] text-mc-caption text-mc-danger",
  composerTop: "composer-topline flex items-center justify-between gap-mc-3 text-mc-caption text-mc-muted [&>span:first-child]:font-mc-semibold",
  composerRow: "composer-input-row flex items-end gap-mc-2",
  textarea: "min-h-[52px] flex-1 resize-none border-0 bg-transparent p-mc-2 shadow-none focus:border-transparent focus:shadow-none focus:outline-none",
  send: "send-button grid h-[var(--control-height-lg)] w-[var(--control-height-lg)] flex-none place-items-center self-end rounded-mc-circle border-0 bg-mc-brand text-mc-inverse shadow-mc-xs transition-[background-color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:bg-mc-brand-hover hover:shadow-mc-sm active:translate-y-px disabled:cursor-not-allowed disabled:opacity-50",
  streamStatus: "stream-status inline-flex min-h-[34px] items-center rounded-mc-pill border border-mc-border-subtle bg-mc-subtle px-[10px] py-mc-2 text-[13px] font-mc-bold text-mc-secondary"
} as const;
