export const conversationStyles = {
  sidebar: "conversation-sidebar flex h-full min-h-[0] flex-col gap-mc-4 p-mc-5",
  header: "sidebar-header grid items-start gap-mc-3",
  newButton: "w-full",
  shortcut: "rounded-mc-sm bg-white/15 px-[5px] py-[3px] font-mc-sans text-[10px] leading-none",
  search: "search-field mt-0",
  searchInput: "w-full",
  actions: "conversation-sidebar-actions flex items-center justify-between gap-mc-3",
  actionsLabel: "text-mc-caption font-mc-semibold text-mc-muted",
  clearButton: "min-h-[var(--control-height-sm)] rounded-mc-pill border border-mc-border-subtle bg-transparent px-mc-3 text-mc-caption font-mc-semibold text-mc-danger hover:bg-mc-danger-soft focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus disabled:cursor-not-allowed disabled:opacity-50",
  list: "conversation-list mt-0 flex min-h-[0] flex-1 flex-col gap-mc-2 overflow-y-auto",
  empty: "conversation-empty-state rounded-mc-md border border-dashed border-mc-border bg-mc-subtle p-mc-4 text-mc-muted",
  group: "conversation-group grid gap-mc-1",
  groupAfter: "mt-mc-4",
  groupLabel: "conversation-group-label flex w-full items-center justify-between bg-transparent px-mc-2 py-0 text-mc-badge font-mc-semibold uppercase tracking-[0.02em] text-mc-muted",
  item: "conversation-item group relative grid grid-cols-[minmax(0,1fr)_var(--control-height-sm)] gap-mc-1 rounded-mc-md border border-transparent bg-transparent p-mc-1 shadow-none transition-[background,border-color,box-shadow,transform] duration-[var(--motion-duration-fast)] hover:-translate-y-px hover:bg-mc-hover hover:shadow-mc-xs focus-within:bg-mc-hover",
  itemActive: "active border-mc-border-subtle bg-mc-brand-soft",
  row: "conversation-row grid min-w-[0] grid-cols-[auto_minmax(0,1fr)] items-center gap-mc-2 rounded-mc-sm border-0 bg-transparent p-[6px] text-left text-mc-text hover:bg-mc-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  rowText: "conversation-row-text min-w-[0]",
  rowTitle: "block overflow-hidden text-ellipsis whitespace-nowrap",
  rowTime: "block overflow-hidden text-ellipsis whitespace-nowrap text-mc-caption text-mc-muted",
  menu: "conversation-menu pointer-events-none relative opacity-0 transition-opacity duration-[var(--motion-duration-fast)] group-hover:pointer-events-auto group-hover:opacity-100 group-focus-within:pointer-events-auto group-focus-within:opacity-100",
  menuOpen: "open pointer-events-auto opacity-100",
  menuTrigger: "inline-flex h-[30px] w-[30px] items-center justify-center rounded-mc-sm border border-transparent bg-transparent text-mc-muted hover:border-mc-border hover:bg-mc-surface focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  popover: "conversation-menu-popover absolute right-0 top-[34px] z-[var(--z-dropdown)] grid min-w-[136px] rounded-mc-md border border-mc-border bg-mc-surface p-[6px] shadow-mc-sm",
  popoverButton: "inline-flex items-center gap-mc-2 rounded-mc-sm border-0 bg-transparent p-mc-2 text-left text-mc-text hover:bg-mc-subtle focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-mc-border-focus",
  dangerButton: "danger text-mc-danger"
} as const;
